#pragma config(Motor,  port1,           armMotorRF,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armMotorLF,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armMotorLB,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armMotorRB,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           wristMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,          clawMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 1 Remote -                            *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*  The Group 6 buttons on the top-right of the VEXnet Joystick are used to raise and lower an arm.   *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
	while(1 == 1)
	{

	//Claw Test
	motor[clawMotor] = -60;

		//Driving Motor Control
		motor[leftMotor] = vexRT[Ch3] / 2;
		motor[rightMotor] = vexRT[Ch2] / 2;

		//Arm Control
		if(vexRT[Btn6U] == 1)
		{
			motor[armMotorLF] = 75;
			motor[armMotorLB] = 75;
			motor[armMotorRF] = 75;
			motor[armMotorRB] = 75;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armMotorLF] = -75;
			motor[armMotorLB] = -75;
			motor[armMotorRF] = -75;
			motor[armMotorRB] = -75;
		}
		else
		{
			motor[armMotorLF] = 0;
			motor[armMotorLB] = 0;
			motor[armMotorRF] = 0;
			motor[armMotorRB] = 0;
		}

		//Wrist Control
		if(vexRT[Btn8D] == 1)
		{
			motor[wristMotor] = 60;
		}
		else if(vexRT[Btn8U] == 1)
		{
			motor[wristMotor] = -60;
		}
		else
		{
			motor[wristMotor] = 0;
		}

		//Claw Control
		if(vexRT[Btn5U] == 1)
		{
			motor[clawMotor] = 120;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[clawMotor] = -120;
		}
		else
		{
			motor[clawMotor] = 0;
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
