#pragma config(Motor,  port5,           launchHammerL, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port1,           wheelLF,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           wheelLB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           wheelRF,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           wheelRB,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          liftL,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,           liftR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armR,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,          launchHammerR, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 1 Remote -                            *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*  The Group 6 buttons on the top-right of the VEXnet Joystick are used to raise and lower an arm.   *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

//Toggle One Joystick AWD
int controlTypeVar = 0;

//launchHammerOverride
int launchHammerTimeout;

task buttonToggle()
{
	while(vexRT[Btn8R] == 1)
	{
		//AWD Toggle
		if(controlTypeVar == 0)
		{
			controlTypeVar = 1;
			wait(2);
		}
		else if(controlTypeVar == 1)
		{
			controlTypeVar = 0;
			wait(2);
		}
	}
}

//This will change launchHammerTimeout back after a timeout is reached
task launchHammerButtonWatchDog()
{
	while(1==1)
	{
		if(vexRT[Btn8L] == 0)
		{
			wait(0.5);
			while(vexRT[Btn8L] == 1)
			{
				launchHammerTimeout=1;
			}
		}
		launchHammerTimeout=0;
	}
}


task main()
{
	while(1 == 1)
	{
		//Call ControlType to allow for toggling anytime
		startTask(buttonToggle);

		if(controlTypeVar == 1)
		{
			//Left Stick Control
			motor[wheelLF] = vexRT[Ch3] / 2;
			motor[wheelLB] = vexRT[Ch3] / 2;
			motor[wheelRF] = vexRT[Ch3] / 2;
			motor[wheelRB] = vexRT[Ch3] / 2;

		}
		else
		{
			//2 Stick Control
			motor[wheelLF] = vexRT[Ch3] / 2;
			motor[wheelLB] = vexRT[Ch3] / 2;
			motor[wheelRF] = vexRT[Ch2] / 2;
			motor[wheelRB] = vexRT[Ch2] / 2;
		}

		//Lift Control
		if(vexRT[Btn6U] == 1)
		{
			motor[liftL] = 75;
			motor[liftR] = 75;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[liftL] = -75;
			motor[liftR] = -75;
		}
		else
		{
			motor[liftL] = 0;
			motor[liftR] = 0;
		}

		//Arm Control
		if(vexRT[Btn6D] == 1)
		{
			motor[armL] = 75;
			motor[armR] = 75;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[armL] = -75;
			motor[armR] = -75;
		}
		else
		{
			motor[armL] = 0;
			motor[armR] = 0;
		}

		//Launch Hammer
		if(vexRT[Btn8L] == 1)
		{
			if(launchHammerTimeout == 0)
			{
				motor[launchHammerL] = 127;
				motor[launchHammerR] = 127;
				startTask(launchHammerButtonWatchDog);
			}
			else
			{
				motor[launchHammerL] = -127;
				motor[launchHammerR] = -127;
			}
		}
		else
		{
			motor[launchHammerL] = 0;
			motor[launchHammerR] = 0;
		}
	}
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
