#pragma config(Motor,  port1,           flipper,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           wheelLF,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           wheelLB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           wheelRF,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           wheelRB,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armR,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          launchHammer,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 1 Remote -                            *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*  The Group 6 buttons on the top-right of the VEXnet Joystick are used to raise and lower an arm.   *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

//Toggle One Joystick AWD
int controlTypeVar = 0;

//Launch Hammer Direction Override when < 1
int launchHammerOverride = 0;

task buttonToggle()
{
	while(vexRT[Btn8R] == 1)
	{
		//AWD Toggle
		if(controlTypeVar == 0)
		{
			controlTypeVar = 1;
			wait(2);
		}
		else if(controlTypeVar == 1)
		{
			controlTypeVar = 0;
			wait(2);
		}
	}
}

//This method just detects extra button presses and keeps track of them - launchHammerOverride
task multiButtonPress()
{
	while(true)
	{
		if(vexRT[Btn8L] == 1)
		{
			wait(0.1);
			launchHammerOverride++;
		}
	}
}

//This method does the actual override
task hammerOverride()
{
	//Collect button presses over a small period of time
	startTask(multiButtonPress);
	wait(0.5);
	stopTask(multiButtonPress);

	if(launchHammerOverride > 1)
	{
		motor[launchHammer] = -127;
	}
}

task main()
{
	while(1 == 1)
	{
		//Call ControlType to allow for toggling anytime
		startTask(buttonToggle);

		if(controlTypeVar == 1)
		{
			//Left Stick Control
			motor[wheelLF] = vexRT[Ch3] / 2;
			motor[wheelLB] = vexRT[Ch3] / 2;
			motor[wheelRF] = vexRT[Ch3] / 2;
			motor[wheelRB] = vexRT[Ch3] / 2;

		}
		else
		{
			//2 Stick Control
			motor[wheelLF] = vexRT[Ch3] / 2;
			motor[wheelLB] = vexRT[Ch3] / 2;
			motor[wheelRF] = vexRT[Ch2] / 2;
			motor[wheelRB] = vexRT[Ch2] / 2;
		}

		//Lift Control
		if(vexRT[Btn6U] == 1)
		{
			motor[liftL] = 75;
			motor[liftR] = 75;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[liftL] = -75;
			motor[liftR] = -75;
		}
		else
		{
			motor[liftL] = 0;
			motor[liftR] = 0;
		}

		//Arm Control
		if(vexRT[Btn6D] == 1)
		{
			motor[armL] = 75;
			motor[armR] = 75;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[armL] = -75;
			motor[armR] = -75;
		}
		else
		{
			motor[armL] = 0;
			motor[armR] = 0;
		}

		//Cone Flipper
		if(vexRT[Btn8D] == 1)
		{
			motor[flipper] = -75;
		}
		else if(vexRT[Btn8U] == 1)
		{
			motor[flipper] = 75;
		}
		else
		{
			motor[flipper] = 0;
		}

		//Launch Hammer
		if(vexRT[Btn8L] == 1)
		{
			launchHammerOverride++;
			startTask(hammerOverride);
			if(launchHammerOverride < 2)
			{
				motor[launchHammer] = 127;
			}
		}
		else
		{
			motor[launchHammer] = 0;
		}
	}
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
